package migrations

import (
	"fmt"

	"github.com/pocketbase/pocketbase/core"
	m "github.com/pocketbase/pocketbase/migrations"
)

// Extends stock_adjustments to support controller-driven adjustments. New
// fields:
//
//   - source ('local' | 'controller') — discriminates who initiated the
//     adjustment. 'local' rows are written by the kiosk's own admin UI;
//     'controller' rows arrive via the inventory.adjust command over NATS.
//   - controller_admin_id (text) — PB record ID of the controller admin who
//     issued a remote adjustment. Stored as plain text because controller
//     admins live in the controller's PB DB, not the kiosk's, so a FK would
//     dangle.
//   - command_id (text, unique when non-empty) — UUID generated by the
//     controller per remote request. Anchor of idempotency: a retried
//     command with the same id catches a unique-violation on insert and
//     returns the prior result instead of double-adjusting.
//
// Also relaxes admin to not-required so controller-driven rows can leave
// it null. Existing rows are already populated; no backfill needed.

func init() {
	m.Register(addStockAdjustRemoteUp, addStockAdjustRemoteDown)
}

func addStockAdjustRemoteUp(app core.App) error {
	col, err := app.FindCollectionByNameOrId("stock_adjustments")
	if err != nil {
		// Fresh DB where the prior migration hasn't created the collection
		// yet — the runner applies migrations in timestamp order so this
		// shouldn't happen, but treat as a no-op rather than fail.
		return nil
	}

	if col.Fields.GetByName("source") == nil {
		col.Fields.Add(&core.SelectField{
			Name:      "source",
			Values:    []string{"local", "controller"},
			Required:  true,
			MaxSelect: 1,
		})
	}
	if col.Fields.GetByName("controller_admin_id") == nil {
		col.Fields.Add(&core.TextField{Name: "controller_admin_id"})
	}
	if col.Fields.GetByName("command_id") == nil {
		col.Fields.Add(&core.TextField{Name: "command_id"})
	}

	// Relax admin: still a FK to admins, but optional. The endpoint and
	// PerformStockAdjustment together ensure exactly one of (admin,
	// controller_admin_id) is populated per row.
	if f := col.Fields.GetByName("admin"); f != nil {
		if rel, ok := f.(*core.RelationField); ok {
			rel.Required = false
		}
	}

	// Unique on command_id when present. Empty command_id is allowed
	// (legacy 'local' rows have no UUID); the WHERE filter excludes them
	// from the uniqueness constraint so they can coexist.
	if !hasIndex(col, "idx_stock_adjustments_command_id") {
		col.AddIndex("idx_stock_adjustments_command_id", true,
			"command_id", "command_id != ''")
	}

	if err := app.Save(col); err != nil {
		return fmt.Errorf("save stock_adjustments: %w", err)
	}
	return nil
}

func addStockAdjustRemoteDown(app core.App) error {
	col, err := app.FindCollectionByNameOrId("stock_adjustments")
	if err != nil {
		return nil
	}

	removeIndex(col, "idx_stock_adjustments_command_id")
	for _, name := range []string{"source", "controller_admin_id", "command_id"} {
		if col.Fields.GetByName(name) != nil {
			col.Fields.RemoveByName(name)
		}
	}
	// Restore admin as required.
	if f := col.Fields.GetByName("admin"); f != nil {
		if rel, ok := f.(*core.RelationField); ok {
			rel.Required = true
		}
	}

	if err := app.Save(col); err != nil {
		return fmt.Errorf("save stock_adjustments: %w", err)
	}
	return nil
}
